modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
Overdrive stabilizer modules for Modern Industrialization machines.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "modern_industrialization"
type = "required"
versionRange = "[${modern_industrialization_version},)"
ordering = "AFTER"
side = "BOTH"

